INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (961,'WebApplication','Get window title','{"test-data":null,"element":null,"attribute":null,"from-element":null,"to-element":null}','getTitle','com.testsigma.automator.actions.web.generic.GetWindowTitleAction','window',961,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (13,'WebApplication','Wait until the #{element} is clickable','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','waitUntilElementIsClickable','com.testsigma.automator.actions.web.wait.WaitUntilElementIsClickableAction','wait',13,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (18,'WebApplication','Wait until the #{element} is not visible','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','waitUntilElementIsNotVisible','com.testsigma.automator.actions.web.wait.WaitUntilElementNotVisibleAction','wait',18,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (7,'WebApplication','Wait until the #{element} is visible','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','waitUntilElementIsVisible','com.testsigma.automator.actions.web.wait.WaitUntilElementIsVisibleAction','wait',7,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (8,'WebApplication','Wait until the #{element} is not selected','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','waitUntilElementIsClickable','com.testsigma.automator.actions.web.wait.WaitUntilElementNotSelectedAction','wait',8,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (106,'WebApplication','Click on the Back button in the browser','{"test-data":null,"element":null,"attribute":null,"from-element":null,"to-element":null}','navigateBack','com.testsigma.automator.actions.common.NavigateBackAction','browser',106,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (105,'WebApplication','Click on the Forward button in the browser','{"test-data":null,"element":null,"attribute":null,"from-element":null,"to-element":null}','navigateForward','com.testsigma.automator.actions.common.NavigateForwardAction','browser',105,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (104,'WebApplication','Click on the Refresh button in the browser','{"test-data":null,"element":null,"attribute":null,"from-element":null,"to-element":null}','reloadCurrentPage','com.testsigma.automator.actions.web.generic.ReLoadCurrentPageAction','browser',104,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (96,'WebApplication','Drag the element #{from-element} and drop on the element #{to-element}','{"test-data":null,"element":null,"attribute":null,"from-element":"\\\\#{.*?}","to-element":"\\\\#{.*?}"}','dragAndDrop','com.testsigma.automator.actions.web.generic.DragAndDropAction','draganddrop',96,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (54,'WebApplication','Verify that the element #{element} is checked','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','verifyChecked','com.testsigma.automator.actions.web.verify.VerifyElementCheckedAction','verify',54,0,0,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (20041,'AndroidNative','Verify that the element #{element} is not present','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','verifyAbsent','com.testsigma.automator.actions.mobile.android.verify.VerifyElementAbsentSnippet','verify',0,0,20041,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (20149,'AndroidNative','Verify that the element #{element} is present','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','verifyPresent','com.testsigma.automator.actions.mobile.android.verify.VerifyElementIsAvailableAction','verify',0,0,20049,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (20108,'AndroidNative','Tap on the enter key','{"test-data":null,"element":null,"attribute":null,"from-element":null,"to-element":null}','pressEnterKey','com.testsigma.automator.actions.mobile.android.press.MobileNativePressEnterAction','pressEnterKey',0,0,20108,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (20126,'AndroidNative','Tap on the search key','{"test-data":null,"element":null,"attribute":null,"from-element":null,"to-element":null}','tapSearchKey','com.testsigma.automator.actions.mobile.android.tap.TapOnSearchInKeyboardAction','tapSearchKey',0,0,20108,0,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (30041,'IOSNative','Verify that the element #{element} is not present','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','verifyAbsent','com.testsigma.automator.actions.mobile.ios.verify.VerifyElementAbsenceAction','verify',0,0,0,30041,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (30143,'IOSNative','Verify that the element #{element} is present','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','verifyPresent','com.testsigma.automator.actions.mobile.ios.verify.VerifyElementIsAvailableAction','verify',0,0,0,30143,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`) VALUES (30107,'IOSNative','Tap on the enter key','{"test-data":null,"element":null,"attribute":null,"from-element":null,"to-element":null}','pressEnterKey','com.testsigma.automator.actions.mobile.ios.presskey.PressEnterKeyAction','pressEnterKey',0,0,0,30107,'2021-10-19 19:37:03','2021-10-19 19:37:03',NULL,NULL);


INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (256, 961, 'Get Title of the current Browser window', 'Get Title of the current Browser window', 'https://app.testsigma.com/login', '{}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (12, 13, 'Wait until the Element with given element is clickable', 'In this example, execution will wait until the Element with given UI Identifier "Rejected" is clickable', 'http://opensource.demo.orangehrmlive.com', '{"Rejected": {"type": "id_value", "value": "btnLogin"}}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (17, 18, 'Wait until the Element with given element becomes invisible', 'In this example, execution will wait until the Element with given UI Identifier "Deattach" becomes invisible', 'http://toolsqa.com/automation-practice-switch-windows/', '{"Deattach": {"type": "id_value", "value": "Deattach"}}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (7, 7, 'Wait until the Element with given element is visible', 'In this example, execution will wait until the Element with given UI Identifier "Visible" is visible', 'http://toolsqa.com/automation-practice-switch-windows/', '{"Visible": {"type": "id_value", "value": "invisibility"}}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (8, 8, 'Wait until the Element with given element is selected', 'In this example, execution will wait until the Element with given UI Identifier “Switch Commands” is selected', 'http://toolsqa.com/automation-practice-form/', '{"Switch Commands": {"type": "xpath", "value": "//option[text()=''Switch Commands'']"}}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (91, 106, 'Go back one Page in Browser History from the current Page', 'In this example, we go back one Page from the current Page in Browser History', 'http://opensource.demo.orangehrmlive.com/', '{}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (90, 105, 'Go forward one Page from the current Page in Browser History', 'In this example, we go forward one Page from the current Page in Browser History', 'http://opensource.demo.orangehrmlive.com/', '{}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (89, 104, 'Refresh the current Page | Reload the current Page', 'In this example, we refresh the current Page | reload the current Page', 'http://opensource.demo.orangehrmlive.com/', '{}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (81, 96, 'Drag from first Element with element and drop onto second Element with element', 'In this example, we Drag from first Element with UI Identifier and drop onto second Element with UI Identifier', 'http://demo.guru99.com/test/drag_drop.html', '{"Bank": {"type": "xpath", "value": "//a[text()='' BANK '']"}, "Debit Side": {"type": "xpath", "value": "(//li[@class=''placeholder''])[1]"}}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (44, 54, 'Verify that the given element field is checked', 'In this example, we go forward one Page from the current Page in Browser History', 'https://semantic-ui.com/modules/checkbox.html#checked', '{"CheckBox": {"type": "xpath", "value": "//div[@class=''ui checkbox checked'']/input"}}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');

INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (858, 20149, 'Verify that the element is present', 'In this example, We will verify that the element is present', 'https://app.testsigma.com/', '{\"element\": \"\\\\\\\\#{.*?}\"}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (859, 20041, 'Verify that the element is not present', 'In this example, We will verify that the element is not present', 'https://app.testsigma.com/', '{\"element\": \"\\\\\\\\#{.*?}\"}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (860, 20108, 'Tap on the enter key','In this example, we can Tap on the enter key', 'API Demos', '{}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (861, 20126, 'Tap on the search key','In this example, we can Tap on the search key', 'API Demos', '{}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');


INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (862, 30041, 'Verify that the element is not present', 'In this example, We will verify that the element is not present', 'https://app.testsigma.com/', '{\"element\": \"\\\\\\\\#{.*?}\"}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (863, 30043, 'Verify that the element is present', 'In this example, We will verify that the element is present', 'https://app.testsigma.com/', '{\"element\": \"\\\\\\\\#{.*?}\"}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');
INSERT INTO `natural_text_action_examples` (`id`, `natural_text_action_id`, `description`, `example`, `workspace`, `data`, `created_date`, `updated_date`) VALUES (864, 30107, 'Tap on the enter key','In this example, we can Tap on the enter key', 'API Demos', '{}', '2022-01-28 16:06:57', '2022-01-28 16:06:57');


