INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`)
VALUES (1112,'WebApplication','Capture #{element}','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','elementScreenshot','com.testsigma.automator.actions.web.generic.ElementScreenshotAction','verify,',1112,10228,0,0,'2023-05-05 17:10:03','2023-05-05 17:10:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`)
VALUES (10228,'MobileWeb','Capture #{element}','{"test-data":null,"element":"\\\\#{.*?}","attribute":null,"from-element":null,"to-element":null}','elementScreenshot','com.testsigma.automator.actions.mobile.mobileweb.generic.ElementScreenshotSnippet','verify,',1112,10228,0,0,'2023-05-05 17:10:03','2023-05-05 17:10:03',NULL,NULL);

INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`)
VALUES (1113,'WebApplication','Open new browser window and navigate to ${test-data}','{"test-data":{"test-data":"test-data"},"element":null,"attribute":null,"from-element":null,"to-element":null}','navigateTo','com.testsigma.automator.actions.web.generic.OpenNewBrowserWindowAction','navigate',1113,10229,0,0,'2023-05-05 17:10:03','2023-05-05 17:10:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`)
VALUES (10229,'MobileWeb','Open new browser window and navigate to ${test-data}','{"test-data":{"test-data":"test-data"},"element":null,"attribute":null,"from-element":null,"to-element":null}','navigateTo','com.testsigma.automator.actions.mobile.mobileweb.generic.OpenNewBrowserWindowSnippet','navigate',1113,10229,0,0,'2023-05-05 17:10:03','2023-05-05 17:10:03',NULL,NULL);

INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`)
VALUES (1114,'WebApplication','Store ${test-data} of an #{element} into runtime variable @{attribute}','{"test-data":{"test-data":"xOffset/yOffset/height/width"},"ui-identifier":"\\\\#{.*?}","attribute":"\\\\@{.*?}"}','store','com.testsigma.automator.actions.web.store.StoreElementDimensionsAction','store',1114,10230,0,0,'2023-05-05 17:10:03','2023-05-05 17:10:03',NULL,NULL);
INSERT INTO `natural_text_actions` (`id`, `workspace_type`, `natural_text`, `data`, `display_name`, `snippet_class`, `action`, `import_to_web`, `import_to_mobile_web`, `import_to_android_native`, `import_to_ios_native`, `created_date`, `updated_date`, `allowed_values`, `condition_type`)
VALUES (10230,'MobileWeb','Store ${test-data} of an #{element} into runtime variable @{attribute}','{"test-data":{"test-data":"xOffset/yOffset/height/width"},"ui-identifier":"\\\\#{.*?}","attribute":"\\\\@{.*?}"}','store','com.testsigma.automator.actions.mobile.mobileweb.store.StoreElementDimensionSnippet','store',1114,10230,0,0,'2023-05-05 17:10:03','2023-05-05 17:10:03',NULL,NULL);