--
-- Dumping data for table `test_data`
--
LOCK TABLES `test_data` WRITE;
/*!40000 ALTER TABLE `test_data` DISABLE KEYS */;
INSERT INTO `test_data` (`id`, `version_id`, `test_data`, `test_data_name`, `copied_from`, `passwords`, `created_date`, `updated_date`) VALUES (21,39,'[{\"name\":\"Los Angeles\",\"description\":\"valid\",\"expectedToFail\":false,\"data\":{\"city\":\"Los Angeles\"}},{\"name\":\"Washington, D.C\",\"description\":\"valid\",\"expectedToFail\":false,\"data\":{\"city\":\"Washington, D.C.\"}},{\"name\":\"New York City\",\"description\":\"valid\",\"expectedToFail\":false,\"data\":{\"city\":\"New York City\"}},{\"name\":\"London\",\"description\":\"valid\",\"expectedToFail\":false,\"data\":{\"city\":\"London\"}},{\"name\":\"India\",\"description\":\"Invalid\",\"expectedToFail\":true,\"data\":{\"city\":\"India\"}}]','List of Source & Destination Cities',NULL,NULL,'2019-09-16 06:23:11','2021-12-28 16:41:18');
INSERT INTO `test_data` (`id`, `version_id`, `test_data`, `test_data_name`, `copied_from`, `passwords`, `created_date`, `updated_date`) VALUES (25,43,'[{\"name\":\"Invalid creds\",\"description\":\"invalid\",\"expectedToFail\":true,\"data\":{\"Username\":\"test\",\"Password\":\"pass\"}},{\"name\":\"Invalid creds with special characters\",\"description\":\"invalid\",\"expectedToFail\":true,\"data\":{\"Username\":\"admin@#\",\"Password\":\"admin\"}},{\"name\":\"Invalid creds without special characters\",\"description\":\"invalid\",\"expectedToFail\":true,\"data\":{\"Username\":\"admin1\",\"Password\":\"admin12\"}},{\"name\":\"Valid creds\",\"description\":\"valid\",\"expectedToFail\":false,\"data\":{\"Username\":\"admin\",\"Password\":\"12345\"}}]','Login Credentials',NULL,NULL,'2019-09-16 11:26:27','2021-12-28 16:41:18');
INSERT INTO `test_data` (`id`, `version_id`, `test_data`, `test_data_name`, `copied_from`, `passwords`, `created_date`, `updated_date`) VALUES (26,44,'[{\"name\":\"Invalid\",\"description\":\"Invalid\",\"expectedToFail\":true,\"data\":{\"Username\":\"surendra\",\"email\":\"surendra@gmail.com\",\"Password\":\"demo544\"}},{\"name\":\"Invalid creds with special characters\",\"description\":\"Invalid\",\"expectedToFail\":true,\"data\":{\"Username\":\"chinna\",\"email\":\"chinna@gmail.com\",\"Password\":\"demo0544#*\"}},{\"name\":\"Invalid creds without special characters\",\"description\":\"Invalid\",\"expectedToFail\":true,\"data\":{\"Username\":\"sridhar93\",\"email\":\"sridhar93.kommi@gmail.com\",\"Password\":\"demo\"}},{\"name\":\"Valid\",\"description\":\"Valid\",\"expectedToFail\":false,\"data\":{\"Username\":\"apptest987\",\"email\":\"wordpresstest987@gmail.com\",\"Password\":\"Wordpress321#\"}}]','Login Credentials',NULL,'[]','2019-09-16 11:48:39','2022-01-03 19:45:12');
INSERT INTO `test_data` (`id`, `version_id`, `test_data`, `test_data_name`, `copied_from`, `passwords`, `created_date`, `updated_date`) VALUES (27,45,'[{\"name\":\"Invalid\",\"description\":\"Invalid\",\"expectedToFail\":true,\"data\":{\"Username\":\"surendra@gmail.com\",\"Password\":\"demo544\"}},{\"name\":\"Invalid creds with special characters\",\"description\":\"Invalid\",\"expectedToFail\":true,\"data\":{\"Username\":\"chinna@gmail.com\",\"Password\":\"demo0544#*\"}},{\"name\":\"Invalid creds without special characters\",\"description\":\"Invalid\",\"expectedToFail\":true,\"data\":{\"Username\":\"sridhar@gmail.com\",\"Password\":\"demo\"}},{\"name\":\"Valid\",\"description\":\"Valid\",\"expectedToFail\":false,\"data\":{\"Username\":\"wordpresstest987@gmail.com\",\"Password\":\"Wordpress321#\"}}]','Login Credentials',NULL,'[]','2019-09-16 13:03:57','2022-01-04 15:52:07');
INSERT INTO `test_data` (`id`, `version_id`, `test_data`, `test_data_name`, `copied_from`, `passwords`, `created_date`, `updated_date`) VALUES (32,43,'[{\"name\":\"Los Angeles\",\"description\":\"valid\",\"expectedToFail\":false,\"data\":{\"city\":\"Los Angeles\"}},{\"name\":\"Washington, D.C\",\"description\":\"valid\",\"expectedToFail\":false,\"data\":{\"city\":\"Washington, D.C.\"}},{\"name\":\"New York City\",\"description\":\"valid\",\"expectedToFail\":false,\"data\":{\"city\":\"New York City\"}},{\"name\":\"London\",\"description\":\"valid\",\"expectedToFail\":false,\"data\":{\"city\":\"London\"}},{\"name\":\"India\",\"description\":\"Invalid\",\"expectedToFail\":true,\"data\":{\"city\":\"India\"}}]','List of Source & Destination Cities',NULL,'[]','2019-12-28 15:51:52','2021-12-28 16:41:18');
/*!40000 ALTER TABLE `test_data` ENABLE KEYS */;
UNLOCK TABLES;
