--
-- Dumping data for table `test_cases`
--

LOCK TABLES `test_cases` WRITE;
/*!40000 ALTER TABLE `test_cases` DISABLE KEYS */;
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (137,NULL,NULL,_binary '\0',_binary '\0',1,'Verify login page displaying properly.','Verify login page content','READY',3,NULL,39,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-09-06 06:44:42','2019-09-16 06:16:09');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (138,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify the login with invalid credentials','READY',3,NULL,39,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-09-06 06:56:41','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (139,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify the login with valid credentials','READY',3,NULL,39,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-09-06 07:00:11','2019-09-07 12:04:05');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (140,NULL,NULL,_binary '',_binary '\0',1,'','Search flights by cities (Data Driven)','READY',3,21,39,NULL,NULL,_binary '\0',0,NULL,3275,NULL,NULL,NULL,'2019-09-06 07:02:22','2022-01-07 13:17:10');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (141,NULL,NULL,_binary '\0',_binary '',1,'','Login step group (Reusable Steps)','READY',3,NULL,39,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-09-06 07:03:38','2019-09-16 05:56:54');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (161,NULL,NULL,_binary '\0',_binary '',1,'','Login step group (Reusable Steps)','READY',3,NULL,43,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 11:24:24','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (162,NULL,NULL,_binary '',_binary '\0',1,'','Search flights by cities (Data Driven)','READY',3,32,43,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 11:31:20','2022-01-06 17:19:15');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (163,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify login with invalid credentials','READY',3,NULL,43,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 11:32:41','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (164,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify login with valid credentials','READY',3,NULL,43,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 11:33:02','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (165,NULL,NULL,_binary '\0',_binary '\0',1,'','Search flights','READY',3,NULL,43,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 11:36:17','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (166,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify login page content','READY',3,NULL,43,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 11:41:17','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (167,NULL,NULL,_binary '\0',_binary '',1,'','Login step group (Reusable Steps)','READY',3,NULL,44,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 11:50:01','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (168,NULL,NULL,_binary '\0',_binary '\0',1,'','Login and verify the subscribed plan(Free)','READY',3,NULL,44,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 11:52:54','2022-01-06 23:29:59');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (169,NULL,NULL,_binary '\0',_binary '',1,'','Logout step group (Reusable Steps)','READY',3,NULL,44,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 11:53:07','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (170,NULL,NULL,_binary '',_binary '\0',1,'','Login to multiple accounts (Data Driven)','READY',3,26,44,NULL,NULL,_binary '\0',0,NULL,3234,NULL,NULL,NULL,'2019-09-16 11:56:10','2022-01-07 13:13:52');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (171,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify create a new post','READY',3,NULL,44,NULL,NULL,_binary '\0',0,NULL,3230,NULL,NULL,NULL,'2019-09-16 11:59:28','2022-01-07 13:13:51');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (172,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify edit profile functionality','READY',3,NULL,44,NULL,NULL,_binary '\0',0,NULL,3232,NULL,NULL,NULL,'2019-09-16 12:48:02','2022-01-07 13:13:52');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (173,NULL,NULL,_binary '\0',_binary '',1,'','Login step group (Reusable Steps)','READY',3,NULL,45,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 13:04:21','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (174,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify app launch and Home page','READY',3,NULL,45,NULL,NULL,_binary '\0',0,NULL,3333,NULL,NULL,NULL,'2019-09-16 13:06:54','2022-01-07 13:50:40');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (175,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify login page','READY',3,NULL,45,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 13:10:41','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (177,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify signup','READY',3,NULL,45,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-09-16 13:19:14','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (191,NULL,NULL,_binary '\0',_binary '\0',1,'','Search flights with multiple filters applied','READY',3,21,39,NULL,NULL,_binary '\0',0,NULL,3250,NULL,NULL,NULL,'2019-12-28 15:05:04','2022-01-07 13:17:07');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (193,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify flight booking (Using reusable Step Group)','READY',3,21,39,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-12-28 15:30:31','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (194,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify signup with valid data (using functions to generate test data)','READY',3,NULL,39,NULL,NULL,_binary '\0',0,NULL,3281,NULL,NULL,NULL,'2019-12-28 15:34:56','2022-01-07 13:17:10');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (195,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify Successful Login','READY',3,NULL,39,NULL,NULL,_binary '\0',0,NULL,3284,NULL,NULL,NULL,'2019-12-28 15:42:46','2022-01-07 13:17:10');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (196,NULL,NULL,_binary '\0',_binary '\0',1,'','Search flights with multiple filters applied','READY',3,NULL,43,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-12-28 16:46:06','2019-12-28 18:45:52');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (197,NULL,NULL,_binary '\0',_binary '\0',1,'','delete test','READY',3,NULL,43,NULL,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2019-12-28 17:21:32','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (198,NULL,NULL,_binary '',_binary '\0',1,'','Verify flight booking (Using reusable Step Group)','READY',3,32,43,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-12-28 17:41:17','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (199,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify signup with valid data (using functions to generate test data)','READY',3,NULL,43,NULL,NULL,_binary '\0',0,NULL,3297,NULL,NULL,NULL,'2019-12-28 18:46:29','2022-01-07 13:50:25');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (200,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify Successful Login','READY',3,NULL,43,NULL,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2019-12-28 18:55:35','2021-12-21 12:48:32');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (202,NULL,NULL,_binary '\0',_binary '\0',1,'','Round trip flying (Pre Requisite)','READY',3,NULL,39,NULL,NULL,_binary '\0',0,NULL,3283,NULL,NULL,NULL,'2020-04-29 18:37:55','2022-01-07 13:17:10');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (203,NULL,NULL,_binary '\0',_binary '\0',1,'','Round trip booking','READY',3,NULL,39,202,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2020-04-29 19:45:15','2022-01-06 19:47:30');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (204,NULL,NULL,_binary '\0',_binary '\0',1,'','Round trip booking','READY',3,NULL,43,199,NULL,_binary '\0',0,NULL,3298,NULL,NULL,NULL,'2020-04-30 09:11:11','2022-01-07 13:50:25');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (205,NULL,NULL,_binary '\0',_binary '\0',1,'','Wordpress-create-new-site','READY',3,NULL,44,NULL,NULL,_binary '\0',0,NULL,3231,NULL,NULL,NULL,'2020-04-30 10:26:33','2022-01-07 13:13:52');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (206,NULL,NULL,_binary '\0',_binary '\0',1,'','Post subscribed plan verification','READY',3,NULL,44,205,NULL,_binary '',0,NULL,NULL,NULL,NULL,NULL,'2020-04-30 10:32:03','2022-01-06 23:29:59');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (207,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify app launch and Home page - Failed','READY',3,NULL,45,NULL,NULL,_binary '\0',0,NULL,3324,NULL,NULL,NULL,'2020-04-30 11:37:52','2022-01-07 13:50:37');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (208,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify Home page[Pre-Requisite Testcase failure]','READY',3,NULL,45,207,NULL,_binary '\0',0,NULL,NULL,NULL,NULL,NULL,'2020-04-30 11:39:03','2022-01-03 20:22:01');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (209,NULL,NULL,_binary '\0',_binary '\0',1,'','Wordpress-create-new-site(Failure scenario)','READY',3,NULL,44,NULL,205,_binary '\0',0,NULL,3233,NULL,NULL,NULL,'2021-12-29 21:53:42','2022-01-07 13:13:52');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (210,NULL,NULL,_binary '',_binary '\0',1,'','Verify login page-(Data Driven)','READY',3,27,45,NULL,176,_binary '\0',0,NULL,3325,NULL,NULL,NULL,'2022-01-04 15:57:56','2022-01-07 13:50:38');
INSERT INTO `test_cases` (`id`, `start_time`, `end_time`, `is_data_driven`, `is_step_group`, `priority_id`, `description`, `name`, `status`, `type`, `test_data_id`, `workspace_version_id`, `pre_requisite`, `copied_from`, `deleted`, `test_data_start_index`, `test_data_end_index`, `last_run_id`, `draft_at`, `obsolete_at`, `ready_at`, `created_date`, `updated_date`) VALUES (211,NULL,NULL,_binary '\0',_binary '\0',1,'','Verify Login-Failure-case','READY',3,NULL,39,NULL,195,_binary '\0',0,NULL,3264,NULL,NULL,NULL,'2022-01-06 21:41:08','2022-01-07 13:17:08');
/*!40000 ALTER TABLE `test_cases` ENABLE KEYS */;
UNLOCK TABLES;
