name: Agent Zip Build
on:
  workflow_dispatch:
    inputs:
      buildType:
        type: choice
        description: "Build Type"
        required: true
        options:
          - Testing
          - Release
      buildVersion:
        description: "Build Version"
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Set AWS environment
        run: |
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_DEFAULT_OUTPUT=json" >> $GITHUB_ENV
          echo "AWS_ROLE_ARN=${{ secrets.STAGE_AWS_GITHUB_OIDC_ROLE_ARN }}" >> $GITHUB_ENV

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Downloading Packages
        run: |
          mkdir -p $HOME/.testsigma_os
          aws s3 cp s3://hybrid-staging.testsigma.com/testsigma_os $HOME/.testsigma_os --recursive

      - name: Building
        run: |
          if [[ "${{ github.event.inputs.buildType }}" == "Testing" ]]; then
            bash agent/scripts/build.sh --VERSION=v${{ github.event.inputs.buildVersion }} --PUBLISH_TO_GIT=false
          fi
          if [[ "${{ github.event.inputs.buildType }}" == "Release" ]]; then
            bash agent/scripts/build.sh --VERSION=v${{ github.event.inputs.buildVersion }} --PUBLISH_TO_GIT=true
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

